//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heranca.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heranca.Resources.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A aplicação não pôde executar a ação.
        /// </summary>
        public static string AAplicacaoNaoPodeExecutarAAcao {
            get {
                return ResourceManager.GetString("AAplicacaoNaoPodeExecutarAAcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string Bairro {
            get {
                return ResourceManager.GetString("Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixo.
        /// </summary>
        public static string Baixo {
            get {
                return ResourceManager.GetString("Baixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep.
        /// </summary>
        public static string Cep {
            get {
                return ResourceManager.GetString("Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep inválido: {0}.
        /// </summary>
        public static string CepInvalido {
            get {
                return ResourceManager.GetString("CepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave não encontrada no WebConfig.AppSettings.
        /// </summary>
        public static string ChaveNaoEncontradaNoWebConfigAppSettings {
            get {
                return ResourceManager.GetString("ChaveNaoEncontradaNoWebConfigAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string Cidade {
            get {
                return ResourceManager.GetString("Cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidades.
        /// </summary>
        public static string Cidades {
            get {
                return ResourceManager.GetString("Cidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string Cnpj {
            get {
                return ResourceManager.GetString("Cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido: {0}.
        /// </summary>
        public static string CnpjInvalido {
            get {
                return ResourceManager.GetString("CnpjInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string Cpf {
            get {
                return ResourceManager.GetString("Cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf inválido: {0}.
        /// </summary>
        public static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDD.
        /// </summary>
        public static string Ddd {
            get {
                return ResourceManager.GetString("Ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string Fornecedor {
            get {
                return ResourceManager.GetString("Fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscrição Estadual.
        /// </summary>
        public static string InscricaoEstadual {
            get {
                return ResourceManager.GetString("InscricaoEstadual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string Logradouro {
            get {
                return ResourceManager.GetString("Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há registros no banco de dados.
        /// </summary>
        public static string NaoHaRegistrosNoBancoDeDados {
            get {
                return ResourceManager.GetString("NaoHaRegistrosNoBancoDeDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo.
        /// </summary>
        public static string NomeCompleto {
            get {
                return ResourceManager.GetString("NomeCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório.
        /// </summary>
        public static string OCampoEObrigatorio {
            get {
                return ResourceManager.GetString("OCampoEObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro não pode ser excluído por conter relacionamentos.
        /// </summary>
        public static string ORegistroNaoPodeSerExcluidoPorConterRelacionamentos {
            get {
                return ResourceManager.GetString("ORegistroNaoPodeSerExcluidoPorConterRelacionamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os valores de {0} devem ser iguais.
        /// </summary>
        public static string OsValoresDeXDevemSerIgual {
            get {
                return ResourceManager.GetString("OsValoresDeXDevemSerIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor de {0} é {1} e o valor máximo permitido é de {2}.
        /// </summary>
        public static string OValorDeXEDeYEOvalorMaximoPermitidoEDeZ {
            get {
                return ResourceManager.GetString("OValorDeXEDeYEOvalorMaximoPermitidoEDeZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social.
        /// </summary>
        public static string RazaoSocial {
            get {
                return ResourceManager.GetString("RazaoSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado.
        /// </summary>
        public static string RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma UF para ver suas cidades.
        /// </summary>
        public static string SelecioneUmaUfParaVerSuasCidades {
            get {
                return ResourceManager.GetString("SelecioneUmaUfParaVerSuasCidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string Sigla {
            get {
                return ResourceManager.GetString("Sigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente ativos.
        /// </summary>
        public static string SomenteAtivos {
            get {
                return ResourceManager.GetString("SomenteAtivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente números.
        /// </summary>
        public static string SomenteNumeros {
            get {
                return ResourceManager.GetString("SomenteNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja excluir este registro?.
        /// </summary>
        public static string TemCertezaQueDesejaExcluirEsteRegistro {
            get {
                return ResourceManager.GetString("TemCertezaQueDesejaExcluirEsteRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uf.
        /// </summary>
        public static string Uf {
            get {
                return ResourceManager.GetString("Uf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF&apos;s.
        /// </summary>
        public static string Ufs {
            get {
                return ResourceManager.GetString("Ufs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário responsável.
        /// </summary>
        public static string UsuarioResponsavel {
            get {
                return ResourceManager.GetString("UsuarioResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        public static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deve ter entre {1} e {2} caracteres.
        /// </summary>
        public static string ValorDeveTerEntreXeYCaracteres {
            get {
                return ResourceManager.GetString("ValorDeveTerEntreXeYCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é inválido!.
        /// </summary>
        public static string ValorEhInvalido {
            get {
                return ResourceManager.GetString("ValorEhInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório.
        /// </summary>
        public static string ValorEhObrigatorio {
            get {
                return ResourceManager.GetString("ValorEhObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ID é inválido.
        /// </summary>
        public static string ValorIdEhInvalido {
            get {
                return ResourceManager.GetString("ValorIdEhInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não pode estar inativo.
        /// </summary>
        public static string ValorNaoPodeEstarInativo {
            get {
                return ResourceManager.GetString("ValorNaoPodeEstarInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não pode ser negativo.
        /// </summary>
        public static string ValorNaoPodeSerNegativo {
            get {
                return ResourceManager.GetString("ValorNaoPodeSerNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não pode ser nulo.
        /// </summary>
        public static string ValorNaoPodeSerNulo {
            get {
                return ResourceManager.GetString("ValorNaoPodeSerNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não pode ter mais que {1} caracteres.
        /// </summary>
        public static string ValorNaoPodeTerMaisQueXCaracteres {
            get {
                return ResourceManager.GetString("ValorNaoPodeTerMaisQueXCaracteres", resourceCulture);
            }
        }
    }
}
